frase = 'Curso em vídeo python'
print(frase)
print(frase[3])
print(frase[3:13])
print(frase[:13])
print(frase[1:15:2])
print(frase[::2])
print(frase.count('o'))
print(frase.upper().count('O'))
print(len(frase))
print(frase.replace('python', 'android'))
print(frase.find('Curso'))
print(frase.lower().find('vídeo'))
print(frase.split())
dividido = frase.split()
print(len(dividido[0]))